# Generated by Django 5.1.6 on 2025-03-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_chapa_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
