# Generated by Django 5.1.6 on 2025-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Format: https://www.youtube.com/watch?v=VIDEO_ID', max_length=2000, null=True),
        ),
    ]
