# Generated by Django 5.1.6 on 2025-03-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
    ]
