# Generated by Django 5.1.6 on 2025-03-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='Course',
            new_name='course',
        ),
    ]
