# Generated by Django 5.1.6 on 2025-03-01 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_reviewrating_courses_rev_user_id_bbf528_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewrating',
            name='courses_rev_user_id_bbf528_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('user', 'course')},
        ),
    ]
