# Generated by Django 5.1.6 on 2025-03-01 23:50

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_reviewrating_courses_rev_user_id_bbf528_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddIndex(
            model_name='reviewrating',
            index=models.Index(fields=['user', 'course'], name='courses_rev_user_id_bbf528_idx'),
        ),
    ]
